function renderStrategy(){const me=team(state.config.mine);$("strategy").innerHTML="PDCA".split("").map(r=>{const target=plannedRoleBudget(r),spent=roleSpent(me,r),left=target-spent;return `<div class="strategy-item"><div class="strategy-line"><div><b>${r}</b><div class="note">Piano ${target} · spesi ${spent} · slot ${slotsLeft(me,r)} · inflazione ${fmtPct(inflation(r))}</div></div><b>${left}</b></div></div>`}).join("");const fav=state.favorites.map(n=>PLAYERS.find(p=>p.name===n)).filter(Boolean).filter(p=>!soldEntry(p.name)).sort((a,b)=>b.fvm-a.fvm);$("favorites").innerHTML=fav.length?fav.map(p=>`<button class="fav-chip" data-pick="${esc(p.name)}">${p.role} · ${esc(p.name)} · ${p.base600}</button>`).join(""):'<span class="note">Nessun giocatore osservato.</span>';document.querySelectorAll("[data-pick]").forEach(b=>b.addEventListener("click",()=>selectPlayer(b.dataset.pick)))}
function renderHistory(){$("history").innerHTML=state.history.length?[...state.history].reverse().map(h=>`<div class="history-row"><div><b>${esc(h.player)}</b><div class="note">${h.role} · ${esc(h.team)}</div></div><b>${h.price}</b></div>`).join(""):'<div class="note">Nessun acquisto registrato.</div>'}
function renderAll(){renderSelectors();renderStats();renderAuction();renderTeams();renderPlayers();renderStrategy();renderHistory();saveState()}
function selectPlayer(name){$("auctionPlayer").value=name;const last=lastBid(name);$("currentBid").value=last?.price||1;if(last)$("bidder").value=last.team;renderAuction();window.scrollTo({top:0,behavior:"smooth"})}
function changeBid(d){$("currentBid").value=Math.max(1,(parseInt($("currentBid").value)||1)+d);renderAuction()}
function recordBid(){const p=playerByName($("auctionPlayer").value),price=+$("currentBid").value||0,teamName=$("bidder").value;if(!p)return toast("Seleziona un calciatore.");if(soldEntry(p.name))return toast("Giocatore già assegnato.");const t=team(teamName);if(slotsLeft(t,p.role)<=0)return toast(`${teamName}: ruolo completo.`);if(price>maxAffordable(t))return toast(`${teamName} non può arrivare a ${price}.`);const last=lastBid(p.name);if(last&&price<=last.price)return toast(`Il rilancio deve superare ${last.price}.`);if(last&&last.team===teamName)return toast(`${teamName} è già leader.`);state.bidEvents.push({player:p.name,role:p.role,team:teamName,price,ts:Date.now()});saveState();renderAuction();toast(`Rilancio: ${teamName} a ${price}`)}
function undoBid(){const p=playerByName($("auctionPlayer").value);if(!p)return toast("Seleziona un giocatore.");for(let i=state.bidEvents.length-1;i>=0;i--)if(state.bidEvents[i].player===p.name){const r=state.bidEvents.splice(i,1)[0],last=lastBid(p.name);$("currentBid").value=last?.price||1;if(last)$("bidder").value=last.team;saveState();renderAuction();return toast(`Annullato ${r.team} a ${r.price}`)}toast("Nessun rilancio da annullare.")}
function assign(teamName){const p=playerByName($("auctionPlayer").value),price=+$("currentBid").value||0;if(!p)return toast("Seleziona un calciatore.");if(soldEntry(p.name))return toast("Giocatore già assegnato.");const t=team(teamName);if(slotsLeft(t,p.role)<=0)return toast(`${teamName}: ruolo completo.`);if(price<1||price>maxAffordable(t))return toast("Prezzo non valido per questa squadra.");const last=lastBid(p.name);if(!last||last.team!==teamName||last.price!==price)state.bidEvents.push({player:p.name,role:p.role,team:teamName,price,ts:Date.now()});t.spent+=price;t.roster.push({player:p.name,role:p.role,price});state.history.push({player:p.name,role:p.role,team:teamName,price,ts:Date.now()});$("auctionPlayer").value="";$("currentBid").value=1;renderAll()}
function undoPurchase(){const h=state.history.pop();if(!h)return toast("Nessun acquisto da annullare.");const t=team(h.team);t.spent-=h.price;const i=t.roster.findIndex(x=>x.player===h.player);if(i>=0)t.roster.splice(i,1);renderAll();toast(`Annullato acquisto di ${h.player}`)}
function toggleFav(name){const i=state.favorites.indexOf(name);i>=0?state.favorites.splice(i,1):state.favorites.push(name);renderPlayers();renderStrategy();renderAuction();saveState()}
function exportBackup(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="fantasta-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{state=normalizeState(JSON.parse(r.result));renderAll();toast("Backup importato.")}catch{toast("Backup non valido.")}};r.readAsText(file)}
function openConfig(){const c=state.config;$("cfgCredits").value=c.initialCredits;$("cfgMine").value=c.mine;$("cfgP").value=c.slots.P;$("cfgD").value=c.slots.D;$("cfgC").value=c.slots.C;$("cfgA").value=c.slots.A;$("bp").value=c.budgetPct.P;$("bd").value=c.budgetPct.D;$("bc").value=c.budgetPct.C;$("ba").value=c.budgetPct.A;$("configDialog").showModal()}
function saveConfig(){const b={P:+$("bp").value||0,D:+$("bd").value||0,C:+$("bc").value||0,A:+$("ba").value||0};if(Object.values(b).reduce((a,x)=>a+x,0)!==100)return toast("Le percentuali devono sommare a 100.");state.config.initialCredits=+$("cfgCredits").value||600;state.config.mine=$("cfgMine").value;state.config.slots={P:+$("cfgP").value||0,D:+$("cfgD").value||0,C:+$("cfgC").value||0,A:+$("cfgA").value||0};state.config.budgetPct=b;$("configDialog").close();renderAll()}
["search","roleFilter","tierFilter","statusFilter","sortBy"].forEach(id=>$(id).addEventListener("input",renderPlayers));
$("auctionPlayer").addEventListener("change",()=>{const p=playerByName($("auctionPlayer").value);if(p)selectPlayer(p.name);else renderAuction()});$("auctionPlayer").addEventListener("input",renderAuction);$("currentBid").addEventListener("input",renderAuction);
$("bidMinus").onclick=()=>changeBid(-1);$("bidPlus").onclick=()=>changeBid(1);$("recordBidBtn").onclick=recordBid;$("undoBidBtn").onclick=undoBid;$("assignMineBtn").onclick=()=>assign(state.config.mine);$("assignTeamBtn").onclick=()=>assign($("bidder").value);$("undoPurchaseBtn").onclick=undoPurchase;$("favBtn").onclick=()=>{const p=playerByName($("auctionPlayer").value);if(p)toggleFav(p.name)};$("exportBtn").onclick=exportBackup;$("importFile").onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$("configBtn").onclick=openConfig;$("closeConfigBtn").onclick=()=>$("configDialog").close();$("saveConfigBtn").onclick=saveConfig;$("resetBtn").onclick=()=>{if(confirm("Azzerare tutta l'asta?")){state=clone(DEFAULT_STATE);localStorage.removeItem(STORAGE_KEY);renderAll()}};
renderAll();
