const PLAYERS=(window.PLAYER_CHUNKS||[]).flat().map(r=>({id:r[0],name:r[1],role:r[2],mantra:r[3],club:r[4],quot:r[5],fvm:r[6],tier:r[7],base600:r[8],baseMax:r[9]}));
const TEAMS=["AC Rullano","AS Quadra","Masterchef United","TEAM90","Cartagine FC","I Socic","IGORMITI","Sporting Madonna","Fc impossibile 3.0","AC Kaiser"];
const STORAGE_KEY="fantasta_clean_v1",OLD_KEY="fantasta_sporting_madonna_2026_27_v2";
const DEFAULT_STATE={config:{initialCredits:600,mine:"Sporting Madonna",slots:{P:3,D:8,C:8,A:6},budgetPct:{P:8,D:15,C:27,A:50}},teams:TEAMS.map(name=>({name,spent:0,roster:[]})),history:[],favorites:[],bidEvents:[]};
function clone(x){return JSON.parse(JSON.stringify(x))}
function normalizeState(s){if(!s||typeof s!=="object")return clone(DEFAULT_STATE);s.config=s.config||clone(DEFAULT_STATE.config);s.config.initialCredits=Number(s.config.initialCredits)||600;s.config.mine=s.config.mine||"Sporting Madonna";s.config.slots=Object.assign({P:3,D:8,C:8,A:6},s.config.slots||{});s.config.budgetPct=Object.assign({P:8,D:15,C:27,A:50},s.config.budgetPct||{});const byName=new Map((s.teams||[]).map(t=>[t.name,t]));s.teams=TEAMS.map(name=>{const t=byName.get(name)||{name,spent:0,roster:[]};t.spent=Number(t.spent)||0;t.roster=Array.isArray(t.roster)?t.roster:[];return t});s.history=Array.isArray(s.history)?s.history:[];s.favorites=Array.isArray(s.favorites)?s.favorites:[];s.bidEvents=Array.isArray(s.bidEvents)?s.bidEvents:[];return s}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(OLD_KEY);return normalizeState(raw?JSON.parse(raw):clone(DEFAULT_STATE))}catch{return clone(DEFAULT_STATE)}}
let state=loadState();function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(msg){const e=$("toast");e.textContent=msg;e.style.display="block";clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.display="none",2200)}
function team(name){return state.teams.find(t=>t.name===name)}function playerByName(name){const q=String(name||"").trim().toLowerCase();return PLAYERS.find(p=>p.name.toLowerCase()===q)}function soldEntry(name){for(let i=state.history.length-1;i>=0;i--)if(state.history[i].player===name)return state.history[i];return null}
function roleCount(t,r){return t.roster.filter(x=>x.role===r).length}function slotsLeft(t,r){return Math.max(0,(state.config.slots[r]||0)-roleCount(t,r))}function totalSlotsLeft(t){return "PDCA".split("").reduce((s,r)=>s+slotsLeft(t,r),0)}function creditsLeft(t){return state.config.initialCredits-t.spent}function maxAffordable(t){return Math.max(0,creditsLeft(t)-Math.max(0,totalSlotsLeft(t)-1))}function roleSpent(t,r){return t.roster.filter(x=>x.role===r).reduce((s,x)=>s+x.price,0)}function plannedRoleBudget(r){return Math.round(state.config.initialCredits*(state.config.budgetPct[r]||0)/100)}function fmtPct(v){const n=Math.round(v*100);return(n>0?"+":"")+n+"%"}function isFav(name){return state.favorites.includes(name)}function bids(name){return state.bidEvents.filter(x=>x.player===name).sort((a,b)=>a.ts-b.ts)}function lastBid(name){const a=bids(name);return a.length?a[a.length-1]:null}
function inflation(role){const vals=[];for(const h of state.history){if(role&&h.role!==role)continue;const p=PLAYERS.find(x=>x.name===h.player);if(p&&p.base600>0)vals.push(clamp(h.price/p.base600,.55,1.65))}return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length-1:0}
function teamCap(t,p){if(!t||!p||slotsLeft(t,p.role)<=0)return 0;return maxAffordable(t)}
function dynamicMax(p){const me=team(state.config.mine);if(!p||!me||slotsLeft(me,p.role)<=0)return 0;const inf=clamp(inflation(p.role),-.15,.35)*.75+clamp(inflation(),-.10,.20)*.25;const roleLeft=Math.max(0,plannedRoleBudget(p.role)-roleSpent(me,p.role)),roleReserve=Math.max(0,slotsLeft(me,p.role)-1);let v=Math.round(p.baseMax*(1+inf));if(roleLeft>roleReserve)v=Math.min(v,roleLeft-roleReserve);return Math.max(0,Math.min(v,maxAffordable(me)))}
function estimateMax(t,p){if(!t||!p||slotsLeft(t,p.role)<=0)return 0;if(t.name===state.config.mine)return dynamicMax(p);const cap=teamCap(t,p);if(cap<=0)return 0;const inf=clamp(inflation(p.role),-.15,.35)*.75+clamp(inflation(),-.10,.20)*.25;const slots=Math.max(1,totalSlotsLeft(t)),startSlots=Math.max(1,Object.values(state.config.slots).reduce((a,b)=>a+b,0)),startFree=Math.max(1,(state.config.initialCredits-startSlots)/startSlots),free=Math.max(0,(creditsLeft(t)-slots)/slots),liquidity=clamp(.82+.18*(free/startFree),.78,1.25),target=Math.max(1,plannedRoleBudget(p.role)),budgetRatio=clamp((target-roleSpent(t,p.role))/target,-.5,1.5),openRatio=(state.config.slots[p.role]||1)?slotsLeft(t,p.role)/(state.config.slots[p.role]||1):0,need=clamp(.86+.16*openRatio+.08*budgetRatio,.82,1.18);return Math.max(0,Math.min(cap,Math.round(p.baseMax*(1+inf)*liquidity*need)))}
function pairStats(teamName,playerName=null){const out={againstMe:0,byMeAgainst:0,total:0,onPlayer:0,avgJump:0},grouped={};let jump=0,jumps=0;for(const e of state.bidEvents){(grouped[e.player]||(grouped[e.player]=[])).push(e);if(e.team===teamName){out.total++;if(!playerName||e.player===playerName)out.onPlayer++}}for(const[pn,raw]of Object.entries(grouped)){if(playerName&&pn!==playerName)continue;const a=raw.slice().sort((x,y)=>x.ts-y.ts);for(let i=1;i<a.length;i++){const prev=a[i-1],cur=a[i];if(cur.team===teamName){jump+=Math.max(0,cur.price-prev.price);jumps++}if(teamName!==state.config.mine&&cur.team===teamName&&prev.team===state.config.mine)out.againstMe++;if(teamName!==state.config.mine&&cur.team===state.config.mine&&prev.team===teamName)out.byMeAgainst++}}out.avgJump=jumps?jump/jumps:0;return out}
function purchasePower(t,p,bid){const cap=teamCap(t,p),est=estimateMax(t,p);if(cap<=bid||cap<=0)return 0;const room=Math.max(0,est-bid),roomPart=50*(clamp(room/Math.max(1,p.baseMax),0,1.2)/1.2),slots=Math.max(1,totalSlotsLeft(t)),startSlots=Math.max(1,Object.values(state.config.slots).reduce((a,b)=>a+b,0)),startFree=Math.max(1,(state.config.initialCredits-startSlots)/startSlots),free=Math.max(0,(creditsLeft(t)-slots)/slots),liquidity=24*(clamp(free/startFree,0,1.5)/1.5),need=16*clamp(slotsLeft(t,p.role)/Math.max(1,state.config.slots[p.role]||1),0,1),st=pairStats(t.name,p.name),behavior=10*Math.min(1,(st.onPlayer+st.againstMe*.75)/3);return Math.round(clamp(roomPart+liquidity+need+behavior,0,100))}
function threatInfo(t,p,bid){if(slotsLeft(t,p.role)<=0)return{cls:"out",label:"RUOLO COMPLETO"};if(teamCap(t,p)<=bid)return{cls:"out",label:"FUORI GIOCO"};if(t.name===state.config.mine)return{cls:"mine",label:"SPORTING MADONNA"};const score=purchasePower(t,p,bid),est=estimateMax(t,p),my=dynamicMax(p);if(est>my&&score>=60)return{cls:"high",label:"PUÒ SUPERARTI"};if(score>=70)return{cls:"high",label:"MINACCIA ALTA"};if(score>=42)return{cls:"medium",label:"MINACCIA MEDIA"};return{cls:"low",label:"MINACCIA BASSA"}}
function pressureLimit(t,p,bid){return Math.max(0,Math.min(dynamicMax(p),estimateMax(t,p)-1,Math.max(bid+1,p.base600)))}
function signalFor(p,bid){if(!p)return{cls:"neutral",text:"Seleziona un giocatore",help:""};const sold=soldEntry(p.name);if(sold)return{cls:"bad",text:"GIÀ ASSEGNATO",help:`${sold.team} per ${sold.price}`};const max=dynamicMax(p),me=team(state.config.mine);if(slotsLeft(me,p.role)<=0)return{cls:"bad",text:"LASCIA - ruolo completo",help:"Non hai più slot nel ruolo."};if(max<=0)return{cls:"bad",text:"LASCIA - budget non disponibile",help:"Devi conservare almeno 1 credito per gli slot residui."};if(bid<=p.base600)return{cls:"good",text:`RILANCIA - sotto il target ${p.base600}`,help:`Massimo dinamico ${max}. Inflazione ${p.role}: ${fmtPct(inflation(p.role))}.`};if(bid<=max)return{cls:"warn",text:`VALUTA - non superare ${max}`,help:"Se sali oltre, il costo compromette il piano attuale."};return{cls:"bad",text:`LASCIA - oltre il massimo ${max}`,help:`Prezzo ${bid}; target su 600: ${p.base600}.`}}
